# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='website_pics'),
        ),
    ]
