# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_site_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
